/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppInicioRouteImport } from './routes/_app/inicio'
import { Route as AuthCriarContaRouteImport } from './routes/_auth/criar-conta'
import { Route as AuthEntrarRouteImport } from './routes/_auth/entrar'
import { Route as AppCarteirasIndexRouteImport } from './routes/_app/carteiras/index'
import { Route as AppCarteirasNovaRouteImport } from './routes/_app/carteiras/nova'
import { Route as AppCarteirasWalletIdIndexRouteImport } from './routes/_app/carteiras/$walletId/index'
import { Route as AppCarteirasWalletIdExtratoRouteImport } from './routes/_app/carteiras/$walletId/extrato'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AuthCriarContaRoute = AuthCriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEntrarRoute = AuthEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => AuthRoute,
} as any)
const AppCarteirasIndexRoute = AppCarteirasIndexRouteImport.update({
  id: '/carteiras/',
  path: '/carteiras/',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteirasNovaRoute = AppCarteirasNovaRouteImport.update({
  id: '/carteiras/nova',
  path: '/carteiras/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteirasWalletIdIndexRoute =
  AppCarteirasWalletIdIndexRouteImport.update({
    id: '/carteiras/$walletId/',
    path: '/carteiras/$walletId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCarteirasWalletIdExtratoRoute =
  AppCarteirasWalletIdExtratoRouteImport.update({
    id: '/carteiras/$walletId/extrato',
    path: '/carteiras/$walletId/extrato',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inicio': typeof AppInicioRoute
  '/criar-conta': typeof AuthCriarContaRoute
  '/entrar': typeof AuthEntrarRoute
  '/carteiras/nova': typeof AppCarteirasNovaRoute
  '/carteiras/': typeof AppCarteirasIndexRoute
  '/carteiras/$walletId/extrato': typeof AppCarteirasWalletIdExtratoRoute
  '/carteiras/$walletId/': typeof AppCarteirasWalletIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inicio': typeof AppInicioRoute
  '/criar-conta': typeof AuthCriarContaRoute
  '/entrar': typeof AuthEntrarRoute
  '/carteiras/nova': typeof AppCarteirasNovaRoute
  '/carteiras': typeof AppCarteirasIndexRoute
  '/carteiras/$walletId/extrato': typeof AppCarteirasWalletIdExtratoRoute
  '/carteiras/$walletId': typeof AppCarteirasWalletIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/inicio': typeof AppInicioRoute
  '/_auth/criar-conta': typeof AuthCriarContaRoute
  '/_auth/entrar': typeof AuthEntrarRoute
  '/_app/carteiras/nova': typeof AppCarteirasNovaRoute
  '/_app/carteiras/': typeof AppCarteirasIndexRoute
  '/_app/carteiras/$walletId/extrato': typeof AppCarteirasWalletIdExtratoRoute
  '/_app/carteiras/$walletId/': typeof AppCarteirasWalletIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inicio'
    | '/criar-conta'
    | '/entrar'
    | '/carteiras/nova'
    | '/carteiras/'
    | '/carteiras/$walletId/extrato'
    | '/carteiras/$walletId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/criar-conta'
    | '/entrar'
    | '/carteiras/nova'
    | '/carteiras'
    | '/carteiras/$walletId/extrato'
    | '/carteiras/$walletId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/inicio'
    | '/_auth/criar-conta'
    | '/_auth/entrar'
    | '/_app/carteiras/nova'
    | '/_app/carteiras/'
    | '/_app/carteiras/$walletId/extrato'
    | '/_app/carteiras/$walletId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/criar-conta': {
      id: '/_auth/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof AuthCriarContaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/entrar': {
      id: '/_auth/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof AuthEntrarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/carteiras/': {
      id: '/_app/carteiras/'
      path: '/carteiras'
      fullPath: '/carteiras/'
      preLoaderRoute: typeof AppCarteirasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carteiras/nova': {
      id: '/_app/carteiras/nova'
      path: '/carteiras/nova'
      fullPath: '/carteiras/nova'
      preLoaderRoute: typeof AppCarteirasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carteiras/$walletId/': {
      id: '/_app/carteiras/$walletId/'
      path: '/carteiras/$walletId'
      fullPath: '/carteiras/$walletId/'
      preLoaderRoute: typeof AppCarteirasWalletIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/carteiras/$walletId/extrato': {
      id: '/_app/carteiras/$walletId/extrato'
      path: '/carteiras/$walletId/extrato'
      fullPath: '/carteiras/$walletId/extrato'
      preLoaderRoute: typeof AppCarteirasWalletIdExtratoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInicioRoute: typeof AppInicioRoute
  AppCarteirasNovaRoute: typeof AppCarteirasNovaRoute
  AppCarteirasIndexRoute: typeof AppCarteirasIndexRoute
  AppCarteirasWalletIdExtratoRoute: typeof AppCarteirasWalletIdExtratoRoute
  AppCarteirasWalletIdIndexRoute: typeof AppCarteirasWalletIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInicioRoute: AppInicioRoute,
  AppCarteirasNovaRoute: AppCarteirasNovaRoute,
  AppCarteirasIndexRoute: AppCarteirasIndexRoute,
  AppCarteirasWalletIdExtratoRoute: AppCarteirasWalletIdExtratoRoute,
  AppCarteirasWalletIdIndexRoute: AppCarteirasWalletIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCriarContaRoute: typeof AuthCriarContaRoute
  AuthEntrarRoute: typeof AuthEntrarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCriarContaRoute: AuthCriarContaRoute,
  AuthEntrarRoute: AuthEntrarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
